# Generated by Django 3.0.8 on 2020-09-27 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='donation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 10, 48, 34, 785662), verbose_name='Date of Donation'),
        ),
    ]
