# Generated by Django 3.0.8 on 2020-09-27 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_auto_20200927_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('fullname', models.TextField(max_length=200)),
                ('email', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zipcode', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='itamname',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='itemname',
            field=models.CharField(default='--', max_length=120, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='donation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 11, 16, 13, 35402), verbose_name='Date of Donation'),
        ),
    ]
